version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: riskmate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: riskmate_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: riskmate_redis
    ports:
      - "6379:6379"

  csharp-api:
    build:
      context: ./RiskMate.MathEngine
      dockerfile: RiskMate.Api/Dockerfile
    container_name: riskmate_csharp_api
    ports:
      - "5266:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=riskmate_db;Username=postgres;Password=supersecretpassword
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - RiskMateSettings__GeminiApiKey=${GEMINI_API_KEY}
      - RiskMateSettings__PythonApiUrl=http://python-ml:8000
    depends_on:
      - db
      - redis

  csharp-worker:
    build:
      context: ./RiskMate.MathEngine
      dockerfile: RiskMate.Worker/Dockerfile
    container_name: riskmate_csharp_worker
    environment:
      - ConnectionStrings__Redis=redis:6379
      - RiskMateSettings__GeminiApiKey=${GEMINI_API_KEY}
      - RiskMateSettings__PythonApiUrl=http://python-ml:8000
    depends_on:
      - redis
      - python-ml

  python-ml:
    build:
      context: ./riskmate-ai-service
      dockerfile: Dockerfile
    container_name: riskmate_python_ml
    ports:
      - "8000:8000"
    volumes:
      - ./riskmate-ai-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./riskmate-front
      dockerfile: Dockerfile
      target: build
    container_name: riskmate_frontend
    ports:
      - "5173:5173"
    environment:
      - PROXY_API_URL=http://csharp-api:8080
    volumes:
      - ./riskmate-front:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - csharp-api

volumes:
  pgdata:
